// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2VtF7LknNiN0nZrDhWFOkcczxEjGZLGw',
    appId: '1:86460470404:web:c0bae1e6a5731fd67d9ed1',
    messagingSenderId: '86460470404',
    projectId: 'greenerai',
    authDomain: 'greenerai.firebaseapp.com',
    storageBucket: 'greenerai.appspot.com',
    measurementId: 'G-ZECNBJHTLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDocw3QesUEOwg4g2BN3q9jKTVqpY9C2SI',
    appId: '1:86460470404:android:ed0be025162daba97d9ed1',
    messagingSenderId: '86460470404',
    projectId: 'greenerai',
    storageBucket: 'greenerai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJ40h6g2LI1jp0Uo_-b32qp_r36ZedDk',
    appId: '1:86460470404:ios:3e9f2f7bf73b464a7d9ed1',
    messagingSenderId: '86460470404',
    projectId: 'greenerai',
    storageBucket: 'greenerai.appspot.com',
    iosBundleId: 'com.mycompany.greenerplus',
  );
}
